### ISSUE TITLE
PLEASE UPDATE ALL FUNCTIONS

### ISSUE THREAD

**Issue by ivanlewis** [mason-mcglothlin/SharpNoty#1]
PLEASE UPDATE ALL FUNCTIONS

**Comment by mason-mcglothlin** [comment]
@ivanlewis  You're going to have to be more specific. What do you mean "update all functions"? Is something not working? Then you should clarify what.

**Comment by mason-mcglothlin** [comment]
@ivanlewis  I closed this issue due to lack of response.

**Comment by ivanlewis** [comment]
if i set timeout 0 its just showing and disappearing. how make it visible till I manually close it.

**Comment by mason-mcglothlin** [comment]
@ivanlewis You're going to need to provide the code you're using. See [How to create a Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve).
